# vim:sw=2:ts=2
# action name
name: 'phoenix-runner-long'

# action description
description: 'Runs Phoenix-RTOS tests, including long tests'

inputs:
  target:
    description: 'Specifies target to run tests'
    default: 'ia32-generic-qemu'
    required: false


# action runner
runs:
  using: 'docker'
  image: 'phoenixrtos/devel'
  entrypoint: ./phoenix-rtos-tests/runner.py
  args:
    - '-T${{ inputs.target }}'
    - '--long-test'


# branding
branding:
  icon: terminal
  color: green
