# vim:sw=2:ts=2
name: ci

on:
  push:
    branches:
      - master
      - 'feature/*'
  pull_request:
    branches:
      - master
      - 'feature/*'

jobs:
  pic-2:
    uses: ./.github/workflows/ci-project.yml
    with:
      nightly: true
      build_params: all tests
      libphoenix_nopic: n
    secrets: inherit
